apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: reddit-background-viewer
  description: r404
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: user:sparksis